### ISSUE TITLE
question: models

### ISSUE THREAD

**Issue by kalle07** [MNeMoNiCuZ/joy-caption-batch#14]
which models i can use which format and where is the save folder

can i use these models ?
blip2, WD14, Deepdanbooru ...

is it in future possible to use GGUF models ?
like llava
https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf

**Comment by MNeMoNiCuZ** [comment]
No. This is for joy-caption only.
You can send the python script to ChatGPT and ask it to rewrite it to support other formats, like blip, WD14, or GGUF models, but it's nothing this project will support.

I may create a UI in the future that combines more models into the same UI, but for now these features are not planned to be supported.
