### ISSUE TITLE
hint: VLLM

### ISSUE THREAD

**Issue by kalle07** [MNeMoNiCuZ/joy-caption-batch#16]
iam not that much in python but 
yes, it would be very convenient to have a prompt for the captions, maybe also a neg-prompt
and its possible the force seed? so now its every time bit different...

is that helping ?

https://docs.vllm.ai/en/v0.2.7/getting_started/quickstart.html
https://qwen.readthedocs.io/en/latest/deployment/vllm.html
https://ploomber.io/blog/vllm-deploy/

**Comment by MNeMoNiCuZ** [comment]
Thanks for sharing the links.

This looks like something else unrelated to joy-caption-batch.
This project and code will only be about joy-caption.
So this project will not deal with vllm. But I will check it out and maybe test it myself.

Here are some other batch processing models I have made similar scripts for:
https://github.com/MNeMoNiCuZ/miaoshouai-tagger-batch
https://github.com/MNeMoNiCuZ/qwen2-caption-batch
https://github.com/MNeMoNiCuZ/florence2-caption-batch
https://github.com/MNeMoNiCuZ/joytag-batch

If you want to be able to prompt the caption, your best bet is qwen2 or moondream.
Currently, my favorite one is the miaoshouai. It lets you choose between many different types of captioning, and I included a random variant, which I think is a good way of captioning for Flux models.

You can check them all out there or from my [github repositories section](https://github.com/MNeMoNiCuZ?tab=repositories).

**Comment by kalle07** [comment]
I thought that was what it was for

![grafik](https://github.com/user-attachments/assets/18b93cd4-7d14-4c0d-baa5-02b9d1122583)


for the models maybe you can write a hint if they are useful for adult stuff

**Comment by MNeMoNiCuZ** [comment]
As you can see from the comment there at the end, "Changing this doesn't seem to matter. Help plz?"
I later learned that this prompt doesn't serve a purpose. The model isn't trained on listening to prompts. It will always output the same. I left this code in here as it was part of the original inference code.

But you can safely trust that this prompt does nothing.
Qwen2 or Moondream lets you prompt.

However, there's a new version of JoyCaption ([Alpha One](https://huggingface.co/spaces/fancyfeast/joy-caption-alpha-one)) which has more options. But still not enough for you to manually prompt it.

**Comment by kalle07** [comment]
all fine , sry for disturbance  ;)
