### ISSUE TITLE
Request: Add support for batch processing

### ISSUE THREAD

**Issue by kalle07** [MNeMoNiCuZ/joy-caption-batch#17]
so for now i work with low-vram

VRAM is 8GB and free 8GB
and the GPU load is only 40%
can i raise up the batch size

**Comment by MNeMoNiCuZ** [comment]
I think you could do that, but I haven't added support for it.
You can ask ChatGPT. Send it the code and ask it to add batch support for it.

I'll edit the title and leave the request open as it's a good feature to add to the project.

**Comment by kalle07** [comment]
but here
https://github.com/MNeMoNiCuZ/miaoshouai-tagger-batch

# Generation parameters
REPETITION_PENALTY = 1.3  # Penalty for repeating phrases, float ~1.5
TEMPERATURE = 0.7  # Sampling temperature to control randomness
TOP_K = 50  # Top-k sampling to limit number of potential next tokens
BATCH_SIZE = 7  # How many images to process at one time

you have done it, is that different ?

**Comment by MNeMoNiCuZ** [comment]
> you have done it, is that different ?

Not me, I haven't coded almost anything here.
My good friend ChatGPT does.

It could be different. I don't know if this model will work with different batch sizes.
It's very likely that it does. That all models using the transformer architecture supports it. I just don't know it.

Which is why I suggest that you try it.

Copy all code that is connected to the BATCH_SIZE variable into this script and see if it works.
And if it does, you can write about it in here, and I'll update the script for you and everyone else.

**Comment by kalle07** [comment]
sry iam only a suggesting

i know you can learn a bit python with chatGPT but thats too much for me  ;)

**Comment by MNeMoNiCuZ** [comment]
> sry iam only a suggesting

No problem. It looked like you were poking around in the code.
It's usually not too hard, especially if you get the support of a capable LLM.

**Comment by kalle07** [comment]
hey, may you can copy paste some parts  ;)

https://huggingface.co/spaces/fancyfeast/joy-caption-alpha-two/tree/main

**Comment by MNeMoNiCuZ** [comment]
I've added batch processing to both alpha2 and prealpha.
Could you please give it a shot and tell me if it works for you.

**Comment by kalle07** [comment]
hmmm   , no low_vram mode ?
so it loads automatc the large 16GB+ model

if it works any hints to use all these options like "Write a descriptive caption for this image in a formal tone."


you have intention to work on this?
https://civitai.com/articles/7794/joycaption-alpha-two-gui-mod

allready rudimental GUI

**Comment by MNeMoNiCuZ** [comment]
> hmmm , no low_vram mode ? so it loads automatc the large 16GB+ model
> 
> if it works any hints to use all these options like "Write a descriptive caption for this image in a formal tone."
> 
> you have intention to work on this? https://civitai.com/articles/7794/joycaption-alpha-two-gui-mod
> 
> allready rudimental GUI

What are you talking about @kalle07?

This is a topic for batch processing.
You requested it. I have added it. Did you test it?

---

I could not get low_vram to work on alpha 2. So it's only there for prealpha.
Please stick to the topic.

And no, I have no intention of working on that GUI.

I'll be making a different UI/tool for a multitude of models at some point.
I couldn't really get that one to work.

**Comment by kalle07** [comment]
no test because 16GB model dont work with 12GB VRAM  ;)

so the other UI/Tool works because low_vram-option , it downloads a 6GB model

**Comment by MNeMoNiCuZ** [comment]
> no test because 16GB model dont work with 12GB VRAM ;)
> 
> so the other UI/Tool works because low_vram-option , it downloads a 6GB model

Ahh, I get you now :)
Alright, closing for now. Separate issue for low vram. I tried making it but I couldn't get it working.
