### ISSUE TITLE
is there any change i can get the example images without caption on it?

### ISSUE THREAD

**Issue by kq-chen** [MNeMoNiCuZ/joy-caption-batch#18]
thanks for your wonderful work! The sample shown in the readme is amazing too.
I am wondering if i can get these example images without caption on it? Thanks.

**Comment by MNeMoNiCuZ** [comment]
Do you want the images?
![2024-04-17 - 14 31 14](https://github.com/user-attachments/assets/2b34208e-aeda-4d28-81ad-e36f4d4c1233)
![2024-04-17 - 21 03 57](https://github.com/user-attachments/assets/c85d5ce4-1107-4fa9-9654-a14c0bd2727f)

**Comment by MNeMoNiCuZ** [comment]
https://github.com/user-attachments/assets/93a62148-5fba-45ed-81ee-26252eeb176e

**Comment by kq-chen** [comment]
thanks!
