### ISSUE TITLE
No module named 'spaces'

### ISSUE THREAD

**Issue by lunar-studio** [MNeMoNiCuZ/joy-caption-batch#19]
I get this from the start on Win 11:

(base) C:\AI Toolkit\joy caption batch\joy-caption-batch>py batch.py
Traceback (most recent call last):
  File "C:\AI Toolkit\joy caption batch\joy-caption-batch\batch.py", line 1, in <module>
    import spaces
ModuleNotFoundError: No module named 'spaces'

**Comment by MNeMoNiCuZ** [comment]
It sounds like you need to install the requirements.

Did you set up a virtual environments according to the Setup steps:
https://github.com/MNeMoNiCuZ/joy-caption-batch?tab=readme-ov-file#setup

Please follow step 3 there.
