### ISSUE TITLE
WEBP images will be excluded. (bug)

### ISSUE THREAD

**Issue by forestsource** [MNeMoNiCuZ/joy-caption-batch#3]
https://github.com/MNeMoNiCuZ/joy-caption-batch/blob/main/batch.py#L68-L76

before:
['.jpg', '.jpeg', '.png', '.bmp', '.gif', 'webp']

after:
['.jpg', '.jpeg', '.png', '.bmp', '.gif', '.webp']

need a comma with webp

**Comment by MNeMoNiCuZ** [comment]
Thank you!
Fixed in:

https://github.com/MNeMoNiCuZ/joy-caption-batch/commit/c5d43816591a1c7eee1ccb6756274b2f4306d7d3
